name: mediastore_resolver
description: Zamienia sciezke pliku audio na content:// URI z MediaStore (dziala tez w silniku headless, np. przy starcie z Android Auto).
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.beagleappsstudio.mediastore_resolver
        pluginClass: MediastoreResolverPlugin
